name: ommiquiz-app

services:
  - name: backend
    source_dir: backend
    github:
      repo: pemo11/ommiquiz
      branch: main
    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1
    envs:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
      - key: ENVIRONMENT
        value: "production"
    routes:
      - path: /api

static_sites:
  - name: frontend
    source_dir: frontend
    github:
      repo: pemo11/ommiquiz
      branch: main
    build_command: npm ci && CI=false npm run build
    output_dir: build
    environment_slug: node-js
    envs:
      - key: REACT_APP_API_URL
        value: "${backend.PUBLIC_URL}/api"
      - key: NODE_ENV
        value: "production"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: CI
        value: "false"
    routes:
      - path: /
    catchall_document: index.html
