name: ommiquiz-app
services:
  - name: backend
    source_dir: /backend
    github:
      repo: pemo11/ommiquiz
      branch: main
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health
    envs:
      - key: PYTHONUNBUFFERED
        value: "1"

  - name: frontend
    source_dir: /frontend
    github:
      repo: pemo11/ommiquiz
      branch: main
    build_command: npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 80
    envs:
      - key: REACT_APP_API_URL
        value: "${backend.PUBLIC_URL}"
    routes:
      - path: /